/localization_hack:
  ros__parameters:
    map_frame: map
    base_link_frame: base_link
    buffer_size: 5
    datum: "37.91530097224505,-122.33385852782446,-26.513797709718347"
    rate_millis: 50
    use_sim_time: true
    debug: false
